package multicast.senseup.awareness.situation;

declare Message
    message : String
    status : Integer
end

rule "Hello World"
    dialect "mvel"
    when
        m : Message( status == 1, $message : message )
    then
        System.out.println( $message ); 
        modify ( m ) { message = "Goodbye cruel world",
                       status = 2 };
end

rule "Good Bye"
    when
        Message( status == 2, $message : message )
    then
        System.out.println( $message ); 
end 


